appName: cartservice
appReplicas: 1
imageName: gcr.io/google-samples/microservices-demo/cartservice
imageTag: v0.2.3
containerPort: 7070
serviceType: ClusterIP
containerEnvVars:
  - name: PORT
    value: "7070"
  - name: REDIS_ADDR
    value: "redis-cart:6379"

servicePort: 7070
