#!/usr/bin/env groovy

pipeline {
    agent any
    stages {
        stage('automate server configuration') {
            steps {
               script {
                    echo 'use ansible to provision web application server'
                    // withCredentials([sshUserPrivateKey(credentialsId: "5ab977e3-5128-4912-95d3-650908bee6d2", keyFileVariable: 'keyfile')]) {
                    //     sh '''
                    //         cd ansible
                    //         pwd
                    //         ls -l
                    //         ansible-playbook --private-key ${keyfile}, --user ec2-user playbook.yaml
                    //     '''
                    // }
               }
            }
        }
        stage('Spin up kubernetes cluster with worker groups') {
            steps {
                script {
                    echo 'spin up kube cluster using terraform'
                    sh '''#!/bin/bash
                        cd terraform
                        pwd
                        ls -l
                        terraform init
                        terraform apply -auto-approve
                        export K8S_AUTH_KUBECONFIG=../terraform/kubeconfig_terraform-eks-cluster
                    '''
                }
            }
        }
        stage('deploy') {
            steps {
                script {
                   echo 'automate infra configuring using ansible - connect to kubecluster and install helm charts'

                //    def shellCmd = "bash ./server-cmds.sh ${IMAGE_NAME}"
                //    def ec2Instance = "ec2-user@35.180.251.121"

                //    sshagent(['ec2-connect']) {
                //        sh "scp server-cmds.sh ${ec2Instance}:/home/ec2-user"
                //        sh "scp docker-compose.yaml ${ec2Instance}:/home/ec2-user"
                //        sh "ssh -o StrictHostKeyChecking=no ${ec2Instance} ${shellCmd}"
                //    }
                }
            }
        }
    }
}
